baseURL = "https://songxi.site/"
languageCode = "zh-CN"
title = "宋曦的博客"
theme = "maupassant"

[author]
  name = "宋曦"

[params]
  author = "宋曦"
  subtitle = "技术人生"
  keywords = "博客"
  description = "宋曦的博客"

  [params.utteranc]
    enable = true
    repo = "dawnorigin/blog"
    issueTerm = "pathname"
    theme = "github-light"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 99